# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: FreePBX
version: "0.1.9"
slug: freepbx17
description: "FreePBX als Home Assistant OS Add-on"
url: "https://github.com/PooruTorie/hass-addon-freepbx"
arch:
  - amd64

startup: services
init: false
host_network: true
audio: false

map:
    - type: share
      read_only: False

options:
    apache_port: 8080

schema:
    apache_port: "int(1,65535)"

ports_description:
    8080/tcp: "FreePBX Webinterface (konfigurierbar)"