# Emergency debug to force request/response IO into logs
# This is noisy. Intended for diagnosing "no access log" situations.

<IfModule dumpio_module>
    DumpIOInput On
    DumpIOOutput On
    LogLevel dumpio:trace7
</IfModule>

